language: go
go:
- 1.14.x
- 1.15.x
before_install:
- "/bin/bash ./scripts/aws.sh"
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -v ./... -covermode=count -coverprofile=coverage.out
after_script:
- curl -d "repo=github.com/ericmaustin/dyno" https://goreportcard.com/checks
- "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
  - AWS_REGION=us-east-1
  - secure: pi6qBgM0RSvm24sIlHbMX+Aq9Yiqx0FsFaTbXg7A71hqovnwdKRVyAlFkvcaG0ctTIjwfiIho5G9BF8zNM+F3Wz6TZ+J4p5xoVrVxePm3ZkBwb566McNc0qdqK2rhNUAT9aePF4qp14qcvE8mYZanPugRF1rot7T+NID2UGw5pXEP8f4aHmagG+keYwSewdxvR94WpGQoOGV0ufaQ9YDcn5KZEQPOrcVi+KC23F4iv5WUEuUXLxlW09TW6HsHJMXcilm0DCIe0d5GLMPvRwZs5NLA71qITaFj0iojpgVajhCVrprBkXA/a7yqhHh4INcGDxi4hCDgfwHdU4BcWWWnK4ID2xwUuH38b9Lf8dxz/UkU5hMN+UmpIk3eQAYws2CO6IdGG18X09OKlAnaiwpJhTNB58euc7anFcj4IGnIlzJHDMm7clcy3a2/JvRBQweDPJy9ggMMyP3CptCdIp18Lhxok/igANBYpUvjLpZM44nK85GGM8I2BMY5tzRUOE2p3pHbMdkdztOWsDEAIB/2ULY6Mf09rTI+rNTr5BKxzWnwH/Kb1BGKLs5FNhlRpF4NmMir3IXGd3UN5VQ0JvqSVuLKHSzRc9ITpT+XcXiNwcLYWNqiE+4nHz9Ak8ZHq7/qc1SYUqg9YuEtTfMRqYIX8FQHsk6Dcq7ztzCOqiDtL8=
  - secure: az4efhja+Bx6fbz/sN7F5RQdhSEz9PKHWJfToXU+y3qZ7UZ2GBDS0DKFK+rLEjZR3vXRNcN2CBd/l5eLuKkMVQsLk5oXKxinK0uNsBolnGtFcFUXxFqjJ4r+c8cpqVd7TLbh2e8/hLdhnQQLSo4KCdEgFuZrQXDlCv/IIJKID/cXXLNPrZDbg/ST5eJFLpWopcPftbM5NdOTlHu51hGfhu3seAg4kdcSzhtyvvbprdXY8LlPpjLK8Tx6rFAGeqKA8jO2IRzFAyWPmMHzhEfCk4lF0/Y6C+qKWNsvF0A3inHkupI60Qr7Nc9aQ7aa2YCS1kAsoT30enaMh+MdGGl1p3O7th3i5Vl5APBdFBkn8V56rwyOuL7B8XES3XJBTMDclCPAqthOK6NCUn9GxRfamG9PWY0oi56Vxp66l5yjapeEU7FkrnxksUuvCNlvy1a8UyoZCDNvX9lyFvfbBxJ4yPNBGuhkmge2jP1bGOWweg1XGYSVW30RxEDy3y5iqqzMKMJvZ1RCinCIZzbe+B7bsxV3i7MYvTWNeil5Bru+jEn8K1+nE3yh2BVp+n3JeA4QUK7NDbzs6Hn7tyaVZMCYgujswYX4GLYHkJ/1shvu6LkN4L+sfwy59GMX2ZfAPqLQnGVAcDJxjfixRfmzjT6NbH265BjaQ8Gutcd5EdCpFfU=
  - secure: VAUJTLLe+2yuu6HjngD3/iUm3Hx6PCpYfjKD1Nh9bbyyH0biI/v63HXeQbiVrSnjaZd3nNznJS+uQ2vJdkfVc/fuEmdPzwvh5TCj+MsLhnIvJrIFdd82Ptfvd5P2LPedxIpbaSQdhlze6aY5efQ0s5WhU9PbK+y15V+cVLGkiHRpjoYT5sisNsIAccbFKCwMBRVhLn+v39RMB1Qk2lxobpAQdaCeDywCh3IvyH6Q8Fog/8gstgoxutYqDrpqgQ4UoT4o9hzzcGfcDN7Pk61nEfbRPYfjvgqu4VQbrNKyCnBT0AlDLW3V9IHR08luMaCNlMNujhocdKP+5NrVEKTTrRM3AGKMTYIBen3TtOi+ptTVP/oxbN7r02nv/XOmPb3B/K18Z+nHwdkt1idbqFr//IVbpExBycmntgLJjt+bbN0iskP6E834lzDgBYdauHgkxXT1N8sYlv6xSFeMwSIO+4Dzh/YrNS/X8TKlEIQImfDudEcnA80zpZ/dEXOnTUWXS9YygS80z+VuBGfLGlS9UMcOw1GGGTk+GhFfI+ECVK1g9cINxaMCmGJHKBmu7hMRZQcn8kNst79i5gXjeYJWYhdlDGaMI/e2Kr8983gM2oFcp4JKWEGyOyQLA2pLbeb5n/skRjktl2YWud4YTl1tVmHqBxt96lhuw62qP7PeRLc=
branches:
  only:
  - master
