language: go
go:
- 1.15.x
- 1.16.x
before_install:
- "/bin/bash ./scripts/aws.sh"
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -v ./... -p 1 -covermode=count -coverprofile=coverage.out
after_script:
- curl -d "repo=github.com/ericmaustin/dyno" https://goreportcard.com/checks
- "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
  - AWS_REGION=us-east-1
  - secure: leIDdvnK6p5QTRuEscwGQsOTYuoaHNycZZ5WYqgHNG3lY2a1lrFJo5XBGo/upbFVnezk5foBkArmcybHy85wFBijyPU1JmEmYE9FoQmB4scML382QThypZ9B+ylGc/EN+Ivko5mpH6/c5BCl0yQmNrhLeBc5ba8t4JIBnlxM7d8fOdfIx+vsLJmqtTW4/Qw0YnKrH4Tiqa25irAgd0as0oG2aGj/anPBralOtj4RhJOOeK02zh7DKH1KrTSDx0irucUQ/Ly2lP1B89RUAkeBC60ZMjxMab1KVhNI8SH8BtYUbNHt+kZS8DR1YzjMDfPGkLxE62z3equi+FciREkYW7LXfZOI9PiaVNSu5tmMnTulEipML2pMc+SRnjRCE9L+JTXeziVK+R6CQnXyX7swlwMtblq0RGHion2zgCVGo5cKE37RNdN9Kj4xnWIkA/mK7TYuw/FsFBARiCiWbGItQXJczN+lpMNRRY5/ncgFfF459dHdFqnPI/cHlVfbnwXO2U/Cx1I9BKdLu3NF1eM8CrVFk5IVPi9hWn3zTZQ7zJcjj24v7V4WJIhmcor7hBPVQjtTaiHWM7WwJMlNhCr/w7+/7VdjXU0XPl7BgER9bnkQw99aBmMh3OwsNnoS8RD8g38DJinfdHPrZRmMQqIaJqyRrbydC7TZZawnZT/SD+g=
  - secure: k6HLgCNRYXClDJu939ktsnn4J0T5PzYmjpUKbh+8yL7Infkw3wvrOw+Os2GOTIAXxW95MUjUaZm8el/32enAtJepPbUCkFryYd0xxx/ANZqZ8DfH+UGtRNyaC6Vm0atePGf0DtrrChsbwiWcWPenon01UG68JDvOCfl63eE39KskLOX0KvZrxK7URtlIk7Ta4IaYU9HQlxtizr019/0+RvgR8/fu3vUajoDkMtiKCfuJ0CtZgXGZaWpinRszzYOd+ihPVK/s9IbtLGVm3KYx2UdSkOCa/AZUz1lsjyOPLl7cc++qlUnn3P9dNwg+hH3INyRS7DfeO3nyqpKHUzQFbypPLMTvA7ddhxtnEmigQwTo6G2L0CWnxe1bC8DSOnaUemS0eqFJuEeQL3soS986m7tPGJyJsKTredWEcUyoZLV7O6/ko3blPunTCIP1+V7w+vea+1K3ttnneg/6ZzdxBzq32Roinnt6zVghhKV2QAUjYVRdumDg7T+3VRqTgor7yswu3dD4zu9fWhAdioyv7MSmPCgN7GQqTA7bhGEe8Ie10bT0OSk3JgN5YFFG94kIie03YPI5YQ/rt5A7i5IUHivkA/JPTL1zmEZ/fcDYlcx5C4wyNbFGoveALyr6hh318ZXX47/TSpV7Wtrcn4Ez4Rsfkl9WQOBn1TESq77gFTc=
  - secure: mH/g0Shh/DA+tIKcHqAFjsI2THmX9YJ2bcYGuXBM+s7Iut97OngHobn2jZxsfFiWY2cOEG5jnm9Bb2fkCensQnwaw0TlxD+kvj+EMRtjeJGIL82DUrcTZ8Fhc9rbU1+yKYd21LH2YZLbOGKAVr44DBjA17dfy6zsY4iMFM6/M37AcM5BqLylrXJkzCRcNP4zO5EtJVgfQ5mckCLZ7z7AkXtiIuBf43CkbaHQiqwUigjGUMpa4tTpAz2gIU8Bp3pAbEaFTYXdGLcdaDWyJOh+XWiIqdYJ74WKFhDoXhAq9CZX9MgdGbyFkGZEk++ZEJeY/jb4GgcHhN8o5EF7ptxMjjy2/ZopVNeZEgE565OiisWaw8AEkxaj4Xr8L399r7fRQbueXG1JVy/bTb7BUnZLIM6OqoFsszt5x73nTEu+ex18B7962jqNGA89BUf93g7LGVsnbAbGJ6QmVAKwIV4dZoJvx6Vgzo4htWNitLCb70c2oQKk3+KKYoYPpBC653z2LB4puRNpRp02cZ4Anc2VEhg0jXioy0LFIbRSeDiU3urcFaMakaQXMJkRwVx538iPdOpsSTec3UCgbQvBc1d2jjSOnbfRS8P+ojPCDOPghU7I3PWhWA5fmpZp3kcVBRFRtii6vcMMLNbmmqD5FL2PWdM17v6+kF9hewuQmmQP3Lk=
branches:
  only:
  - master
