language: go
go:
- 1.14.x
- 1.15.x
before_install:
- "/bin/bash ./scripts/aws.sh"
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -v ./... -covermode=count -coverprofile=coverage.out
after_script:
- curl -d "repo=github.com/ericmaustin/dyno" https://goreportcard.com/checks
- "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
  - AWS_REGION=us-east-1
  - secure: JYM0v93LUJXM7Y0ECiqoEWkhTfYUahSpt/fdM/v8A5Aod7AbT4pLZGVwitfgqAOp9cvB+w8kYr8dpz7YIniGynGjmlAvkxKJaYAGEUJC1pHwZiyXZm1ZV6UNnSKY0a0Nt7gj2GTvjCgX/8lyqbntjWda0fAjKuMaJ2zA1DkwHOrZ5Qk68li4vS370gTC68bAL9ufbALyOB8xRVXXsXbilGQNMj9Xd9uxgKii7dlrvrJo024zGbJNmJqrFPdMNU+mPD8Le1YUioLhaymOOQjs6bZJLrjjtOOxadwiy5jKez0EJxcPgYcH24z2YgkuFXItrmKU/WPYk+ga7JKuRfNy8sks8N9mY6jtgS3PpVBsQ9cXTv/X68LlDlPc5UOtB/UIfste9btBqQVBOUqlxKSPBb7TpNsJOxQMveS/K2f78W9dEdaKC5na/OP/5nvsg5rTg2EqsLc/3m/QHuv9/lc7KfyYFpU6WKxNHGQA5g9OAJJ+vZNGI/6mVsF+jHvswBEyFTB6kOcrIy1Ct/2dPsX6tbtPIOqI9FTmtV/L0sMcHbAXAn9goenVQjDZoJZCDfdlFVFCUexNDhOjk5643w1BjJAuY3oaBkSFVE5Z1tFlGBieBHbyoJ0q8OkP4NuFuV/yvEdZixbjUybzxADF/oFlcIfdpoavvqefiPHZJvIRH3g=
  - secure: JK1OuCi/j3S5DqFQB3W2Ju5yv0Gq4IfwABIxRZz8XZFU4kg72vfPMzTe9IQSPrijAzf0QvprAkoJJuOQa5e7ofv6Xo3lPxk/PY/iS6HfFmbF2i4g5P0hxdd1Tdcp09OZ43/yslPVx3MvlqBkx32P5awwpPYk2n5Yqo/UFRx6tPuDhK0OGgDu1t0t2FdHgMWPk49WkkzzOSQJaPoChvzPyTjHaEWiplBhZ8Uv4ZnDXvBKtI8npPN6emf0C2vtd1ktj5GTAFuSRH32POGHzMBZQ7jlj8yvvr05x4JiZkuPRJL1pSrZ65czkra3tFXoSO25GmzUE0dq3ar/fi50nu7TFgMcEZP5YybN4ZuiNXhGu6jzgWdvgwVlMGvmGlDEWfMM0ejqQnBSEMa4N+sHP1AkCrBy6c4+ALqqEot4Dr157HDgMMVwDK0XfgKgV2ZF/v0JmJ7v7cp8gYuyUuD5nkSPVD5yeQgj0I8vN1Tc92+GWY0KOWXvcrc7f6OGfus5C1LRm3Ayk3zevkCbgSYfhuiyo++1oB8GvrDq/hZAZ5uMZoTg/ZSvc4ljYGsPCHar7vbs+djSWUuvlNmRV9kkOuTS1jjgzop0K8DzM/dyefhegK+GLcEmtrImKMizniZv25szrY8bvwiXuuwYUd0dAAKdC5zZYBhywM3SlIRZ1Hd3qts=
  - secure: kiymoGxXo1851g99gubYwdVRtxO/wgM9RuNos0+C0rBEtuN/trgUcB2n6DEuXwvSXqik3l5gEV1v3xtOKM/1bf6o7fAFvvHRlShg9amS0yh8RN6TQiW/x6dt4tcxFQu4jTzFG4PnwoHTCw+jFokO12V4wngLyJzCOevAlMSz1WKIwdR4hbkfJZtjUYl53wb5/3ahSu8O+Bnri3rUMIIFMDRm1GZx8bBO+jEukxUmRKuugduKLRtOga1F7/bSpGNgfa4caARxGTveYfh3rojCsfztzNtrGduuC+zNqlfq0bZ0VazLDD6yHHIJCd4fyNXOOs/SSP48v0ppU5mDgCgu+4mRHPVU7p/Drx/HEl1GyXhHJ0D4CqqxnmkagJ1UQKLlgU5eNNa+ct9vQFs6ZmH39v/5a1gr5Kr5ZwhjYfu7mDqqN/WJyKjUgJlEBRf/onRMVnjPUZw4izLkaPdOGJqV5+6E0cffnFr9oEWZvXKZXnlJxQ7wDbRqO6vvfksWJAxGbPiALN38m1/05y4dRGovEa9rvbrUg6OLuGozKh9n2LHQdTQ6/NQczBaronR09Wicr5Ly4smuvlX8NzW+1M0kWXbpjWJvyNa2zoB/LZlnOISp4MFDX9uEBNVG94PVExcdclrU7z0TCsBROOw/78rBwpjBc2dQ0oMujP/0mvvYgJE=
branches:
  only:
  - master
