language: go
go:
- 1.14.x
- 1.15.x
before_install:
- "/bin/bash ./scripts/aws.sh"
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -v ./... -covermode=count -coverprofile=coverage.out
after_script:
- curl -d "repo=github.com/ericmaustin/dyno" https://goreportcard.com/checks
- "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
  - AWS_REGION=us-east-1
  - secure: VNVGKAiNkXzICjyBVr7ctriRqj8VVN6hHvUdAapr5NCzpzh9Nf9BhA37IVfIfyhowmOF9LlMnBjcPuqiYhykmGMm6tfD0jdd0vwre5wuYdhcyqpDsYBwG0u/9qe+85GiyORGRlYbCTVUbFxukmrzsZQ1L3wDMm3lZ+u5hEL9vQoOK0+m6J4wRUphJ52TrZyarBq7E1uRPBterFuqmdXJFyvbGptMMQzVY7SCh6md6ZSIWxHQj+XnGt+QeIEaCDdthZ8dkVMxY5C4x0lpdlFObdKZRw6GXIjoKm5a90MBgzGL7FqlUqr83nTx+T2COcC5PJ7cPgTBn6ss4KsBTvtAmSMBUh43w4s7XcYVnR9ibgjxLa2jSzbUcIJelmhnIFhWQRHafhYCR5MM5Ys7EfkKjjFx+IkqnoFpdo2vIBgMLvPh7oHlF74QSjnnFmRsXEEp0CfdPDHZqgmEXSbfY4A4Ga0f963Kr1ePlcLTeFyqW04tatXifZQ55mxQ+PluWiFRCHjkLoOhwRvbm9mEB4CTLAQ5I/9AqQmBzTAfyFcB2mrC9dy3zoUTqY4uhNqZZ0yF92uSSadiRu39R0Ybm8DViE68IXP//k0zpFiA15mmm+j8XpLrr5SU5ZwwolDAPNVqBouE1g+kKHSV5nP6MukaKd/Lr46u1ageZIkLN1nRwCA=
  - secure: YrTrJ+9Njt+qdUVv3KXbrXXZwcbQ8Hco++cEpBJeY18gDCJphHpqHZ8LljtrXpLXzeP9RLXyqy+R0Ew1bA5ZvyRw/GJt5t3GFwq472Knj4kdUqn+6OaOiNd8afXmkMRoStJqimowU4qxk07Neqie0UXFFFmRgTqay9wDTeE6EudpVuRLaGgN1+0IxPq8zTEdN9szz7Cvq38NHypU96AGdJbEUOpyxfrGfBN39mtUtp1w+gEbWTmFT3z+pMkj2/pEMKRLPcInpTm/aowuyHqExc7cBaxAc+G4Y4KRfsIAMfgNFQdNRneh10/kJh1yNw0BD3DFt3X+8Zq0cD0LxIerntxTVXJr+QOOCXrK+mhnlFAjKIwPFO/hJOgvbUNu9zyoMNK0UOgnp5JrolqqTpBTfVOFHwXz9Quq6TxUrJ9e7UbfhPTv5LC318/4TZmDbFX9k5xOF28hCNwyvkgpnsFrkmjy5bsN1LpllQsniMj0FaUEPCskJD/0PBWvCpH80vhCr7TCwoFlWqT0WlD8uxZB+Fyg9DUzNMt0pSqCns7psxn90q0cWDIYU8lRVim0GnryjkRaC6sgKpGYKV151To1B0dlWHNMeJNIyFwR5ZnJpyloTl90M4dKDcb6IIbn3muImkBJKfGTq8RDcSCoNn/3CjAOE+qraBcyzQXQQDj+c1k=
  - secure: f40rJmHkoGm9SmjP+HMJapvRSL0sROxp26b5X8qWERjz6nnjAQXFfcO0LwMe5TKRRKt5YVX9B51DOWvk+EjglB3czeI3s7RK2sLCoyu+hcvA7mGK+KT3owawcQbLjlsTMDHxu4vAeOZ8yXFHGEG7fwZTGzaWfeSbkL9SCY2RZf+6nU3kXU57womvEk0lCQZU07hvFwm6UCnHAsUfb+ZyzAXvFjt9x57kT9cUWQ4Brpow5YN02FwlYb0BNHsOULy563h2m0YqC1DojtD5fzNRJN9cL7pieZZZOuLpCTDeJD8ljkCyK2RYqVb1m1c/IvPmciaHhnKsQUSSS6CQIEMbpN2b7q8jVlH4rvnuv7w1+q1cbAd2LIZMtYkJ03DAi909HkgMl0PdSfrL1NBK7BYCEe5z6P44jUxbHxM51FP0Az4MVtVMdnEbhPm008eDUmH+dmGaxY9oO37K8+whTsFEQ7aZvZWdUwBM8tX7RP9ayGLyfjUr8NlGHzob3NSbxpZsIxbQR68U+QzWF7DEtTFLAglFohQCXpneM1JcorywN3LC6jMgvb3Tb3lQVuV6KKkEGOQzdD25BG8APgDiqMI7ZDaEqUiPci4fcIYyrL78Kh8ZWjR1GR2cPY4YtOr9TS+Qx1SE+VHBuqTKerwyKWtnFq6Nd5orfTNrLGm1q7MDXUg=
branches:
  only:
  - master
